# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['../run_api_prod.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('src', 'backend/src'),
        ('lib', 'backend/lib'),
        ('../../.venv/Lib/site-packages/prophet/stan_model', 'prophet/stan_model'),
        ('../../.venv/Lib/site-packages/prophet/__version__.py', 'prophet'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.responses',
        'fastapi.exceptions',
        'pydantic',
        'pydantic.fields',
        'pydantic_core',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.orm',
        'asyncpg',
        'psycopg2',
        'pandas',
        'numpy',
        'pyarrow',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'prophet',
        'prophet.serialize',
        'prophet.forecaster',
        'sklearn',
        'sklearn.metrics',
        'sklearn.linear_model',
        'sklearn.preprocessing',
        'sklearn.utils',
        'src.api.app',
        'src.database',
        'src.config',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
    windowed=True
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='api',
)
